# Generated by Django 4.1.3 on 2022-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_trait_pets"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
