# Generated by Django 4.1.3 on 2022-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0005_alter_trait_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
